// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA00knH8i5iHbfKlNRsYwsj5ZZX_atj2rA',
    appId: '1:41841943247:web:ba61928291a4558349cdba',
    messagingSenderId: '41841943247',
    projectId: 'grocery-app-1604c',
    authDomain: 'grocery-app-1604c.firebaseapp.com',
    storageBucket: 'grocery-app-1604c.firebasestorage.app',
    measurementId: 'G-PKN05QDQEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ujFIMV2NPJNqwYUTzzIw6DX39CSxVUY',
    appId: '1:41841943247:android:fcf32a28a9a784bf49cdba',
    messagingSenderId: '41841943247',
    projectId: 'grocery-app-1604c',
    storageBucket: 'grocery-app-1604c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpYrIIzxV3bDliLOBava-xZK3gdWntmjk',
    appId: '1:41841943247:ios:c848822e8c421fad49cdba',
    messagingSenderId: '41841943247',
    projectId: 'grocery-app-1604c',
    storageBucket: 'grocery-app-1604c.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpYrIIzxV3bDliLOBava-xZK3gdWntmjk',
    appId: '1:41841943247:ios:c848822e8c421fad49cdba',
    messagingSenderId: '41841943247',
    projectId: 'grocery-app-1604c',
    storageBucket: 'grocery-app-1604c.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA00knH8i5iHbfKlNRsYwsj5ZZX_atj2rA',
    appId: '1:41841943247:web:5768d7ba3484ece249cdba',
    messagingSenderId: '41841943247',
    projectId: 'grocery-app-1604c',
    authDomain: 'grocery-app-1604c.firebaseapp.com',
    storageBucket: 'grocery-app-1604c.firebasestorage.app',
    measurementId: 'G-F50Z2L7BPE',
  );
}
